### ISSUE TITLE
Running pip3 install on pi results in error

### ISSUE THREAD

**Issue by gordonbrander** [OpenAgInitiative/openag-brain#8]
```
pi@raspberrypi:~/openag-brain $ pip3 install .
Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/pip/__init__.py", line 215, in main
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/local/lib/python3.5/locale.py", line 595, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```

**Comment by gordonbrander** [comment]
Yuck. This appears to be some Ubuntu issue http://stackoverflow.com/questions/36394101/pip-install-locale-error-unsupported-locale-setting.
